top_restaurants = [
    "McDonald's",
    "Starbucks",
    "Chick-fil-A",
    "Taco Bell",
    "Wendy's",
    "Dunkin'",
    "Burger King",
    "Subway",
    "Domino's",
    "Chipotle Mexican Grill",
    "Sonic Drive-In",
    "Panera Bread",
    "Pizza Hut",
    "KFC",
    "Popeyes",
    "Panda Express",
    "Dairy Queen",
    "Arby's",
    "Little Caesars",
    "Olive Garden",
    "Applebee's",
    "Jack in the Box",
    "Buffalo Wild Wings",
    "Texas Roadhouse",
    "Papa Johns",
    "Chili's Grill & Bar",
    "Whataburger",
    "IHOP",
    "Outback Steakhouse",
    "Culver's",
    "Denny's",
    "Cracker Barrel",
    "Raising Cane's Chicken Fingers",
    "Red Lobster",
    "Jimmy John's",
    "The Cheesecake Factory",
    "Zaxby's",
    "LongHorn Steakhouse",
    "Jersey Mike's Subs",
    "Wingstop",
    "Five Guys",
    "Hardee's",
    "In-N-Out Burger",
    "Carl's Jr.",
    "Bojangles",
    "Red Robin",
    "Waffle House",
    "Golden Corral",
    "BJ's Restaurant & Brewhouse",
    "Firehouse Subs",
    "El Pollo Loco",
    "Tropical Smoothie Cafe",
    "P.F. Chang's",
    "Del Taco",
    "Dutch Bros. Coffee",
    "Marco's Pizza",
    "Qdoba Mexican Eats",
    "McAlister's Deli",
    "Hooters",
    "Steak 'n Shake",
    "Krispy Kreme",
    "Papa Murphy's Pizza",
    "TGI Fridays",
    "Church's Chicken",
    "Shake Shack",
    "Freddy's Frozen Custard & Steakburgers",
    "First Watch",
    "Bob Evans",
    "Carrabba's Italian Grill",
    "Baskin-Robbins",
    "Moe's Southwest Grill",
    "Cheddar's Scratch Kitchen",
    "Ruth's Chris Steak House",
    "Checkers",
    "White Castle",
    "Smoothie King",
    "Tim Hortons",
    "MOD Pizza",
    "Yard House",
    "The Habit Burger Grill",
    "Auntie Anne's",
    "Captain D's Seafood Kitchen",
    "Noodles & Company",
    "Bonefish Grill",
    "Portillo's",
    "Jack's Family Restaurants",
    "Jason's Deli",
    "Jamba",
    "Perkins Restaurant & Bakery",
    "Charleys Philly Steaks",
    "California Pizza Kitchen",
    "Hungry Howie's Pizza",
    "Miller's Ale House",
    "The Capital Grille",
    "Cooper's Hawk Winery & Restaurants",
    "Dave & Buster's",
    "Round Table Pizza",
    "Potbelly Sandwich Shop",
    "Einstein Bros. Bagels",
    "Pollo Tropical",
    "Logan's Roadhouse",
    "Cold Stone Creamery",
    "Boston Market",
    "Taco John's",
    "Mellow Mushroom",
    "Twin Peaks",
    "Chuy's",
    "Saltgrass Steak House",
    "Jet's Pizza",
    "Fogo de Chao",
    "Maggiano's Little Italy",
    "O'Charley's",
    "Torchy's Tacos",
    "Wienerschnitzel",
    "Nothing Bundt Cakes",
    "Black Bear Diner",
    "Blaze Pizza",
    "Sweetgreen",
    "Fleming's Prime Steakhouse & Wine Bar",
    "Long John Silver's",
    "Schlotzsky's",
    "Rally's",
    "Caribou Coffee",
    "Topgolf",
    "Dickey's Barbecue Pit",
    "Chuck E. Cheese",
    "Krystal Company",
    "Cafe Rio Mexican Grill",
    "Famous Dave's",
    "HoneyBaked Ham Co.",
    "Fazoli's",
    "Ruby Tuesday",
    "Lazy Dog Restaurant & Bar",
    "Ninety Nine Restaurant & Pub",
    "On The Border Mexican Grill & Cantina",
    "Cicis",
    "Texas de Brazil Churrascaria",
    "Benihana",
    "Pizza Ranch",
    "Godfather's Pizza",
    "Braum's Ice Cream & Dairy Stores",
    "Taco Cabana",
    "Scooter's Coffee",
    "Penn Station East Coast Subs",
    "Chicken Salad Chick",
    "Mountain Mike's Pizza",
    "Seasons 52",
    "Walk-On's Sports Bistreaux",
    "A&W All American Food",
    "Smashburger",
    "Golden Chick",
    "Firebirds Wood Fired Grill",
    "Bahama Breeze Island Grille",
    "Corner Bakery",
    "Sarku Japan",
    "Slim Chickens",
    "Farmer Boys",
    "Uncle Julio's",
    "Cinnabon",
    "Village Inn",
    "Pappadeaux Seafood Kitchen",
    "Wetzel's Pretzels",
    "Huddle House",
    "Donatos Pizza",
    "Fuzzy's Taco Shop",
    "Peet's Coffee",
    "True Food Kitchen",
    "Newk's Eatery",
    "Old Chicago Pizza + Taproom",
    "Rubio's",
    "Ocean Prime",
    "Pei Wei",
    "STK",
    "Cava",
    "Jollibee",
    "Pret A Manger",
    "Sbarro",
    "Morton's The Steakhouse",
    "Mastro's Restaurants",
    "Frisch's Big Boy",
    "Lee's Famous Recipe Chicken",
    "Au Bon Pain",
    "Pollo Campero",
    "Zoes Kitchen",
    "Ono Hawaiian BBQ",
    "Smokey Bones",
    "Wayback Burgers",
    "Biggby Coffee",
    "Sonny's BBQ",
    "LaRosa's Pizzeria",
    "54th Street Restaurant & Drafthouse",
    "Paris Baguette",
    "Bill Miller Bar-B-Q",
    "BonChon",
    "L&L Hawaiian Barbecue",
    "Giordano's",
    "Uno Pizzeria & Grill",
    "NoRTH Italia",
    "Costa Vida Fresh Mexican Grill",
    "Buca di Beppo",
]
